// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-PI3UIUlQDWnppbNy-ae5VfYq9N5rnYs',
    appId: '1:580983625577:web:f330edc5185ff075dacff8',
    messagingSenderId: '580983625577',
    projectId: 'story-app-17311',
    authDomain: 'story-app-17311.firebaseapp.com',
    storageBucket: 'story-app-17311.appspot.com',
    measurementId: 'G-WLMBRFP0YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-YVnWlRsi0olbNpq_QIJlgFZ6mHLaunE',
    appId: '1:580983625577:android:86aa8fe42a3fcc1adacff8',
    messagingSenderId: '580983625577',
    projectId: 'story-app-17311',
    storageBucket: 'story-app-17311.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGRGtXHwz0s0kHSsc0mk6LPbumqpbXuVo',
    appId: '1:580983625577:ios:242396cac656638cdacff8',
    messagingSenderId: '580983625577',
    projectId: 'story-app-17311',
    storageBucket: 'story-app-17311.appspot.com',
    iosBundleId: 'com.example.storyApp',
  );
}
